name: ternary-transformer

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch::pytorch
  - numpy
  - matplotlib
  - jupyter
  - ipykernel
  - tqdm
  - pip
  - pip:
    - sympy
